### ISSUE TITLE
How to simulate the block ? 

### ISSUE THREAD

**Issue by m7mdcc** [Deltik/mod_antiloris#5]
Hi 

I was struggling to simulate a DDoS block. I used the K6 load testing tool, sending 2000 VUs from the same IP within 30 seconds. However, only about 35 connections were blocked.

Is this expected behavior? When I tested mod_evasive with a similar configuration, only around 40 connections were allowed through.

Thanks

**Comment by Deltik** [comment]
@m7mdcc: mod_antiloris protects an Apache HTTP Server from a specific kind of attack called [Slowloris](https://en.m.wikipedia.org/wiki/Slowloris_(cyber_attack)).  When you send thousands of users that make requests normally, those requests terminate quickly and don't open enough connection slots for mod_antiloris to kick in and block additional requests.  It's the number of simultaneous connections that mod_antiloris is tracking, not the frequency of connections.  I would even recommend tuning [the directives](https://github.com/Deltik/mod_antiloris/blob/v0.8.2/README.md#configuration) to reduce the number of rejected connections for your peak load, as legitimate clients that use HTTP connections responsibly should be let through as far as mod_antiloris is concerned.

You can use [SlowHTTPTest](https://www.kali.org/tools/slowhttptest/) to check if a web server is vulnerable to a Slowloris denial-of-service attack.  This tool should also reveal that [mod_evasive is ineffective at preventing single-IP Slowloris attacks](https://github.com/Deltik/mod_antiloris/blob/v0.8.2/README.md#mod_antiloris-vs-mod_evasive).

I'll close this issue as not planned, because what you have described matches the intended behavior of mod_antiloris, but I can continue discussing the test methodology if you have further questions.
